Vagrant.configure("2") do |config|

  # Sistema operativo della VM
  config.vm.box = "generic/ubuntu2204"

  # Nome interno della macchina
  config.vm.hostname = "ansible-es"
  
  config.vm.network "private_network", ip: "192.168.56.10"

  # Configurazione VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.name = "ansible-es"
    vb.memory = 1024
    vb.cpus = 1
  end

  # Installazione automatica di Ansible
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
  SHELL

end