Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu2204"

  config.vm.define "pp1" do |pp1|
    pp1.vm.hostname = "pp1"
    pp1.vm.network "private_network", ip: "192.168.90.91"
  end

  config.vm.define "pp2" do |pp2|
    pp2.vm.hostname = "pp2"
    pp2.vm.network "private_network", ip: "192.168.90.92"

  end 
  
  config.vm.synced_folder "./shared", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.provision "ansible" do |ansible|
  ansible.playbook = "./playbook-provision.yml"

  ansible.groups = {
    "pingpong" => ["pp1", "pp2"]
  }
  end
end
