---
- name: aggiungo utenti 
  hosts: server
  become: true

  vars:
    gruppi:
      - java
      - dev-ops
      - bosses

    utenti:
      - name: tommaso
        home: /home/tommaso
        shell: /bin/bash
        gruppo: java
      
      - name: fabio
        home: /home/fabio
        shell: /bin/bash
        gruppo: dev-ops

      - name: luca
        home: /home/luca
        shell: /bin/bash
        gruppo: bosses

      - name: marco
        home: /home/marco
        shell: /bin/bash
        gruppo: dev-ops
    
  tasks:
    - name: creo gruppi
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
      loop: "{{ gruppi }}"
        
    - name: creo utenti
      ansible.builtin.user:
        name: "{{ item.name }}"
        home: "{{ item.home }}"
        shell: "{{ item.shell }}"
        group: "{{ item.gruppo }}"
        state: present
      loop: "{{ utenti }}"