Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.hostname = "otel-lab"

  config.vm.network "private_network", ip: "192.168.30.30"

  config.vm.synced_folder "./es_bonus/", "/home/vagrant/otel-lab/es_bonus"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end
end