# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|


  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "pecoro-lupolo-cavolo"
  config.vm.synced_folder "./shared_files", "/home/shared"

  config.vm.network "private_network", ip: "192.168.67.67"

  config.vm.synced_folder ".", "/vagrant_data"
  
  config.vm.provider "virtualbox" do |vb|
    vb.name = "lupo-pec-ops"
    vb.cpus = 2
    vb.memory = "2048"
  end
  
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook_setup.yml"
  end
end
