---
- name: Installo pacchetti, configuro server web con file audio
  hosts: all
  become: yes
  gather_facts: false

  tasks:
    - name: Installo pacchetti necessari
      dnf:
        name:
          - httpd
          - sox
          - firewalld
        state: present
      
    - name: Avvio servizio firewalld
      service:
        name: firewalld
        state: started
        enabled: yes
    
    - name: Aggiungo regola firewall per http
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes

    - name: Avvio servizio httpd
      service:
        name: httpd
        state: started
        enabled: yes 
      
    - name: Creo le melodie
      shell: |
        cd /var/www/html
        sox -n -r 44100 -c 2 /var/www/html/la.wav synth 1 sine 440
        sox -n -r 44100 -c 2 /var/www/html/si.wav synth 1 sine 493.88
        sox -n -r 44100 -c 2 /var/www/html/do.wav synth 1 sine 523.25
        sox -n -r 44100 -c 2 /var/www/html/re.wav synth 1 sine 587.33
        sox -n -r 44100 -c 2 /var/www/html/mi.wav synth 1 sine 659.25
        sox -n -r 44100 -c 2 /var/www/html/fa.wav synth 1 sine 698.46
        sox -n -r 44100 -c 2 /var/www/html/sol.wav synth 1 sine 783.99
        sox -n -r 44100 -c 2 /var/www/html/la2.wav synth 1 sine 880

        sox la.wav si.wav do.wav re.wav mi.wav fa.wav sol.wav la2.wav /var/www/html/lam.wav

        sox -n -r 44100 -c 2 /var/www/html/do#.wav synth 1 sine 554.37
        sox -n -r 44100 -c 2 /var/www/html/fa#.wav synth 1 sine 739.99
        sox -n -r 44100 -c 2 /var/www/html/sol#.wav synth 1 sine 830.61

        sox la.wav si.wav do#.wav re.wav mi.wav fa#.wav sol#.wav la2.wav /var/www/html/laM.wav
 
    - name: Aggiungo effetti al file melodia.wav
      shell: |
        sox /var/www/html/lam.wav /var/www/html/lamrev.wav reverb 80 50 100 gain -n -3
        sox /var/www/html/laM.wav /var/www/html/laMrev.wav reverb 80 50 100 gain -n -3
  
    - name: Creo file index.html
      copy:
        dest: /var/www/html/index.html
        content: |
          <!DOCTYPE html>
          <html lang="it">
          <body>
            <h1>Scegli la melodia</h1>
            <p>Clicca sui pulsanti per ascoltare le melodie:</p>
            <p>Devops Everywhere - Es Academy</p>
            <p>Buon ascolto! :)</p>

            <button onclick="playMelodia('lamrev.wav')">La minore</button>
            <button onclick="playMelodia('laMrev.wav')">La maggiore</button>

            <br><br>
            <audio id="melodiaPlayer" controls></audio>

            <script>
              function playMelodia(melodia) {
                const audio = document.getElementById('melodiaPlayer');
                audio.src = melodia;
                audio.play();
              }
            </script>
          </body>
          </html>
