Vagrant.configure("2") do |config|
  config.vm.box = "generic/rocky9"
  config.vm.hostname ="devops-es1"
  config.vm.network "private_network", ip: "192.168.70.70"
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = "1"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "rocky9setup.yml"
  end
end
