# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 
  config.vm.box = "geerlingguy/centos7"

  config.ssh.insert_key = false

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :virtualbox do |v|
    v.memory = 256
    v.linked_clone = true
  end

  #app server 1
  config.vm.define "app1" do |app|
    app.vm.hostname = "orc-app1.test"
    app.vm.network :private_network, ip:"192.168.60.4"
    app.vm.provision "shell", inline: <<-SHELL
      sudo sed -i 's/^#*PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
      sudo sed -i 's/^#*PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
      echo "vagrant:vagrant" | sudo chpasswd
      sudo systemctl restart sshd
    SHELL
  end

    #app server 2
  config.vm.define "app2" do |app|
    app.vm.hostname = "orc-app2.test"
    app.vm.network :private_network, ip:"192.168.60.5"
    app.vm.provision "shell", inline: <<-SHELL
      sudo sed -i 's/^#*PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
      sudo sed -i 's/^#*PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
      echo "vagrant:vagrant" | sudo chpasswd
      sudo systemctl restart sshd
    SHELL
  end

    #app server 3
  config.vm.define "app3" do |app|
    app.vm.hostname = "orc-app3.test"
    app.vm.network :private_network, ip:"192.168.60.6"
    app.vm.provision "shell", inline: <<-SHELL
      sudo sed -i 's/^#*PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
      sudo sed -i 's/^#*PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
      echo "vagrant:vagrant" | sudo chpasswd
      sudo systemctl restart sshd
    SHELL
  end

  
end
